config/routes.rb
Poc::Application.routes.draw do
  resources :activities
  resources :students
  resources :grades
  root :to => "students#index"

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  validates :name, :presence => true
  validates :date, :presence => true
  validates :percentage, :presence => true, :numericality => { :greater_than => 0, :less_than_or_equal_to => 100, :only_integer => true }
  
  has_many :grades, :dependent => :destroy
  
  default_scope order("date ASC")
end

app/models/grade.rb
class Grade < ActiveRecord::Base
  belongs_to :student
  belongs_to :activity
  
  validates :student_id, :activity_id, :presence => true
  
  validates_numericality_of :grade, :less_than_or_equal_to => 5.0, :greater_than_or_equal_to => 0.0, :allow_nil => true
end

app/models/student.rb
# encoding: utf-8
class Student < ActiveRecord::Base
  validates :name, :presence => true
  validates :code, :presence => true, :format => { :with => /^[0-9]{12}$/, :message => "debe estar formado por 12 números" }
  validates :email, :presence => true, :format => { :with => /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i, :message => "no es una dirección de email válida" }
  
  has_many :grades, :dependent => :destroy
  
  def evaluated_percentage
    grades.select { |g| g.grade.present? }.map(&:activity).inject(0) { |sum, activity| sum + activity.percentage }
  end
  
  def first_name
    name.split.first
  end
  
  def grade_for(some_activity)
    grades.where(:activity_id => some_activity.id).first || Grade.new(:student_id => self.id, :activity_id => some_activity.id)
  end
  
  def weighted_average
    present_grades = grades.select { |g| g.grade.present? }
    return "-" if present_grades.empty?
    answer = 0.0
    present_grades.each do |grade|
      answer += grade.grade * grade.activity.percentage / 100.0
    end
    answer.round(2)
  end
end

app/controllers/activities_controller.rb
# encoding: utf-8

class ActivitiesController < ApplicationController
  def index
    @activities = Activity.all
  end

  def show
    @activity = Activity.find(params[:id])
  end

  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.new(params[:activity])
    if @activity.save
      redirect_to students_path, :notice => "Se guardó la actividad."
    else
      render :action => 'new'
    end
  end

  def edit
    @activity = Activity.find(params[:id])
  end

  def update
    @activity = Activity.find(params[:id])
    if @activity.update_attributes(params[:activity])
      redirect_to students_path, :notice => "Se guardaron los cambios."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy
      redirect_to students_path, :notice => "Se borró la actividad."
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  def edit
    @grade = Grade.where(:activity_id => params[:id], :student_id => params[:student_id]).first
    @grade ||= Grade.new(:activity_id => params[:id], :student_id => params[:student_id])
  end
  
  def show
    @grade = Grade.where(:activity_id => params[:id], :student_id => params[:student_id]).first
    @grade ||= Grade.new(:activity_id => params[:id], :student_id => params[:student_id])    
  end
  
  def update
    @grade = Grade.where(:activity_id => params[:id], :student_id => params[:student_id]).first
    @grade ||= Grade.new(:activity_id => params[:id], :student_id => params[:student_id])
    @grade.grade = params[:grade][:grade]
    if @grade.save
      render "show"
    else
      render
    end
  end
end

app/controllers/students_controller.rb
# encoding: utf-8
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(params[:student])
    if @student.save
      redirect_to @student, :notice => "Se creó el estudiante."
    else
      render :action => 'new'
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    if @student.update_attributes(params[:student])
      redirect_to @student, :notice  => "Se guardaron los cambios."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to students_url, :notice => "Se borró el estudiante."
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
  def format_percentage(p)
    content_tag(:span, "#{p}%", :class => (p == 100 ? "green" : "red"))
  end
  
  def percentage_sum
    format_percentage(Activity.sum(:percentage))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Error")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Por favor corrige estos errores y vuelvo a intentarlo.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/activities/_form.html.erb
<%= form_for @activity do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </p>
  <p>
    <%= f.label :percentage %><br />
    <%= f.number_field :percentage %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/activities/edit.html.erb
<% title "Editar Actividad" %>

<div class="block center">
  <%= render 'form' %>
</div>

<p>
  <%= link_to "Volver a la lista de actividades", students_path %>
</p>

app/views/activities/index.html.erb
<% title "Activities" %>

<table>
  <tr>
    <th>Name</th>
    <th>Date</th>
    <th>Percentage</th>
  </tr>
  <% for activity in @activities %>
    <tr>
      <td><%= activity.name %></td>
      <td><%= activity.date %></td>
      <td><%= activity.percentage %></td>
      <td><%= link_to "Show", activity %></td>
      <td><%= link_to "Edit", edit_activity_path(activity) %></td>
      <td><%= link_to "Destroy", activity, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Activity", new_activity_path %></p>

app/views/activities/new.html.erb
<% title "Agregar Nueva Actividad" %>

<div class="block center">
  <%= render 'form' %>
</div>

<p>
  <%= link_to "Volver a la lista de actividades", students_path %>
</p>

app/views/activities/show.html.erb
<% title "Activity" %>

<p>
  <strong>Name:</strong>
  <%= @activity.name %>
</p>
<p>
  <strong>Date:</strong>
  <%= @activity.date %>
</p>
<p>
  <strong>Percentage:</strong>
  <%= @activity.percentage %>
</p>

<p>
  <%= link_to "Edit", edit_activity_path(@activity) %> |
  <%= link_to "Destroy", @activity, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", activities_path %>
</p>

app/views/grades/_form.html.erb
<%= form_for @grade, :url => grade_path(:id => @grade.activity_id, :student_id => @grade.student_id), :method => :put, :remote => true do |f| %>
  <%= f.text_field :grade, :size => 5 %>
  <%= f.submit "OK" %>
  <%= link_to "Cancelar", grade_path(:id => @grade.activity_id, :student_id => @grade.student_id), :remote => true, :class => "cancel" %>
<% end %>

app/views/grades/_grade.html.erb
<%= link_to grade.grade || "-", edit_grade_path(:id => grade.activity_id, :student_id => grade.student_id), :remote => true %>

app/views/grades/edit.js.erb
$("td.grade.activity_<%= @grade.activity_id %>.student_<%= @grade.student_id %>").html("<%= escape_javascript render("form") %>");

app/views/grades/show.js.erb
$("td.grade.activity_<%= @grade.activity_id %>.student_<%= @grade.student_id %>").html("<%= escape_javascript render("grade", :grade => @grade) %>");
$(".weighted_average").html("<%= escape_javascript @grade.student.weighted_average.to_s %>");
$(".graded_percentage").html("<%= escape_javascript @grade.student.evaluated_percentage.to_s %>%");

app/views/grades/update.js.erb
alert("Por favor corrige los siguientes errores: <%= @grade.errors.full_messages.to_sentence %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_for @student do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/students/edit.html.erb
<% title "Editar Estudiante" %>

<div class="block center">
  <%= render 'form' %>
</div>

<p>
  <%= link_to "Detalles", @student %> |
  <%= link_to "Volver a la lista de estudiantes", students_path %>
</p>

app/views/students/index.html.erb
<% title "Estudiantes" %>

<div class="center">
  <% if @students.empty? %>
    No hay ningún estudiante todavía. <%= link_to "Agregar un estudiante", new_student_path %>.
  <% else %>
    <table>
      <tr>
        <th>Nombre</th>
        <th>Código</th>
        <th>Email</th>
        <th>Porcentaje evaluado</th>
        <th>Promedio actual</th>
        <th colspan="2"></th>
      </tr>
      <% for student in @students %>
        <tr>
          <td><%= student.name %></td>
          <td><%= student.code %></td>
          <td><%= student.email %></td>
          <td><b><%= format_percentage student.evaluated_percentage %></b></td>
          <td><b><%= student.weighted_average %></b></td>
          <td><%= link_to "Detalle", student %></td>
          <td><%= link_to "Suprimir", student, :confirm => '¿Estás seguro?', :method => :delete %></td>
        </tr>
      <% end %>
    </table>

    <p><%= link_to "Agregar nuevo estudiante", new_student_path %></p>
  <% end %>
</end>

<h1>Actividades de la materia</h1>
  <% if Activity.all.empty? %>
    No hay ninguna actividad todavía. <%= link_to "Agregar la primera actividad", new_activity_path %>.
  <% else %>
    <table>
      <tr>
        <th>Fecha</th>
        <th>Nombre</th>
        <th>Porcentaje</th>
        <th colspan="2"></th>
      </tr>
      <% for activity in Activity.all %>
        <tr>
          <td><%= l activity.date, :format => :long %></td>
          <td><%= activity.name %></td>
          <td><%= activity.percentage %>%</td>
          <td><%= link_to "Editar", edit_activity_path(activity) %></td>
          <td><%= link_to "Suprimir", activity, :confirm => '¿Estás seguro?', :method => :delete %></td>
        </tr>
      <% end %>
      <tr>
        <td></td>
        <td></td>
        <td><b><%= percentage_sum %><b></td>
        <td colspan="2">
        </td>
      </tr>
    </table>

    <div>
      <% if Activity.sum(:percentage) != 100 %>
        <b>Nota</b>: No se ha ingresado el 100% de las actividades.
      <% end %>
    </div>

    <p><%= link_to "Agregar nueva actividad", new_activity_path %></p>
  <% end %>

app/views/students/new.html.erb
<% title "Agregar nuevo estudiante" %>

<div class="center">
  <div class="block">
    <%= render 'form' %>
  </div>

  <p><%= link_to "Volver a la lista", students_path %></p>
</div>

app/views/students/show.html.erb
<% title @student.name %>

<p>
  <strong>Código:</strong>
  <%= @student.code %>
</p>
<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<h2>Calificaciones</h2>

<p>
  Haz click en alguna celda para modificar la calificación de <%= @student.first_name %> en esa actividad.
</p>

<table class="single_student_grades">
  <tr>
    <th>Actividad</th>
    <th>Porcentaje</th>
    <th>Calificación</th>
  </tr>
  
  <% Activity.all.each do |activity| %>
    <tr>
      <td><%= activity.name %></td>
      <td><%= activity.percentage %>%</td>
      <td class="grade activity_<%= activity.id %> student_<%= @student.id %>">
        <%= render "grades/grade", :grade => @student.grade_for(activity) %>
      </td>
    </tr>
  <% end %>
  <tr>
      <td></td>
      <td class="graded_percentage"><%= @student.evaluated_percentage %>%</td>
      <td class="weighted_average"><%= @student.weighted_average %></td>
  </tr>
</table>

<p>
  <%= link_to "Editar datos básicos", edit_student_path(@student) %> |
  <%= link_to "Suprimir", @student, :confirm => '¿Estás seguro?', :method => :delete %> |
  <%= link_to "Volver a la lista de estudiantes", students_path %>
</p>